
wallpaper {
  monitor = eDP-1
  path = ~/.config/hypr/wallpapers/fallen_order_wallpaper_cropped.png
  fit_mode = cover
}

wallpaper {
  monitor = HDMI-A-1
  path = ~/.config/hypr/wallpapers/fallen_order_wallpaper.png
  fit_mode = cover
}

wallpaper {
  monitor = DP-7
  path = ~/.config/hypr/wallpapers/fallen_order_wallpaper.png
  fit_mode = cover
}

wallpaper {
  monitor = DP-8
  path = ~/.config/hypr/wallpapers/fallen_order_wallpaper.png
  fit_mode = cover
}

splash = false
