# laptop internal display
wallpaper {
  monitor = eDP-1
  path = ~/.config/hypr/wallpapers/fallen_order_wallpaper_cropped.png
  fit_mode = cover
}

# generic external hdmi
wallpaper {
  monitor = HDMI-A-1
  path = ~/.config/hypr/wallpapers/fallen_order_wallpaper.png
  fit_mode = cover
}

# thealt monitor 1
wallpaper {
  monitor = DP-7
  path = ~/.config/hypr/wallpapers/fallen_order_wallpaper.png
  fit_mode = cover
}

# thealt monitor 2
wallpaper {
  monitor = DP-8
  path = ~/.config/hypr/wallpapers/fallen_order_wallpaper.png
  fit_mode = cover
}

# pc
wallpaper {
  monitor = DP-2
  path = ~/.config/hypr/wallpapers/fallen_order_wallpaper.png
  fit_mode = cover
}

# VNC-1
wallpaper {
  monitor = VNC-1
  path = ~/.config/hypr/wallpapers/fallen_order_wallpaper.png
  fit_mode = cover
}

splash = false
